import type { Metadata } from "next";
import { DashboardMenu } from "./_components/dashboard-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col flex-1 w-full page-bg ">
      <DashboardMenu />
      <main className="flex-1 w-full ">
        {children}
      </main>
    </div>
  );
}
