import type { Metadata } from "next";
 
import "./globals.css";
import { EB_Garamond } from "next/font/google";
import { Menu } from "./_components/menu";
import { Footer } from "./_components/footer";

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-eb-garamond",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className="h-full">
      <body
        className={`${ebGaramond.variable} antialiased min-h-screen flex flex-col`}
      >
        <Menu />

        
        <main className="flex-1 w-full">
          {children}
        </main>

        <Footer /> 
        
      </body>
    </html>
  );
}