import type { Metadata } from "next";
 
import "./globals.css";
import { EB_Garamond } from "next/font/google";
 

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-eb-garamond",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className="h-full">
      <body
        className={`${ebGaramond.variable} antialiased min-h-screen flex flex-col bg-gradient-to-br from-background via-[#0F172A] to-blue-tech font-sans dark:bg-black`}
      >
    

        
        <main className="flex-1 w-full ">
          {children}
        </main>

      
        
      </body>
    </html>
  );
}