import type { Metadata } from "next";

import { Menu } from "../_components/menu";
import { Footer } from "../_components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Menu />

      <main className="flex-1 w-full ">{children}</main>

      <Footer />
    </>
  );
}
